// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Session struct {
	Uuid      string `json:"uuid"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

type User struct {
	ID        int64 `json:"id"`
	GithubID  int64 `json:"github_id"`
	CreatedAt int64 `json:"created_at"`
}
